[build]
  publish = "."
  command = "npm install && pip install -r requirements.txt && npm run build"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"